import React, { useEffect, useState } from 'react';
import { Sparkle, Clock, Check } from '@phosphor-icons/react';
import type { CharacterProfile, CharacterRoutineProfile, Worldbook } from '../../types';

const RoutinePanel: React.FC<{ character: CharacterProfile; worldbooks: Worldbook[]; busy?: boolean; onAnalyze: (worldbookIds: string[]) => void; onSave: (profile: CharacterRoutineProfile) => void }> = ({ character, worldbooks, busy, onAnalyze, onSave }) => {
  const [draft, setDraft] = useState<CharacterRoutineProfile | null>(character.routineProfile || null);
  const [selectedBookIds, setSelectedBookIds] = useState<string[]>(character.routineProfile?.sourceWorldbookIds || []);
  useEffect(() => setDraft(character.routineProfile || null), [character.id, character.routineProfile]);
  useEffect(() => setSelectedBookIds(character.routineProfile?.sourceWorldbookIds || []), [character.id, character.routineProfile?.sourceWorldbookIds]);
  const selectedSet = new Set(selectedBookIds);
  const toggleBook = (id: string) => setSelectedBookIds(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const sourceLabels = draft?.sourceWorldbookLabels || worldbooks.filter(book => selectedSet.has(book.id)).map(book => book.title);
  const sourceSummary = sourceLabels.length ? `核心人设 + ${sourceLabels.join('、')}` : '仅核心人设（未选世界书）';
  const sourcePicker = <div className="mt-3 rounded-xl border border-indigo-100 bg-indigo-50/50 p-2.5"><div className="flex items-baseline justify-between gap-2"><p className="text-[10px] font-bold text-indigo-900">AI 识别依据</p><span className="text-[9px] text-indigo-500">可多选</span></div><p className="mt-0.5 text-[10px] leading-relaxed text-indigo-700">核心人设会始终参与；只有勾选的世界书正文会发送给 AI。</p>{worldbooks.length ? <div className="mt-2 max-h-28 space-y-1 overflow-y-auto pr-0.5">{worldbooks.map(book => <button type="button" key={book.id} onClick={() => toggleBook(book.id)} className={`flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left transition-colors ${selectedSet.has(book.id) ? 'bg-white text-indigo-800 shadow-sm' : 'text-slate-600 hover:bg-white/70'}`}><span className={`flex h-4 w-4 shrink-0 items-center justify-center rounded border ${selectedSet.has(book.id) ? 'border-indigo-500 bg-indigo-500 text-white' : 'border-slate-300 bg-white text-transparent'}`}><Check size={11} weight="bold"/></span><span className="min-w-0 flex-1 truncate text-[10px] font-medium">{book.title}</span><span className="shrink-0 text-[9px] text-slate-400">{book.category || '未分类'}</span></button>)}</div> : <p className="mt-2 text-[10px] text-slate-500">还没有可选世界书；这次将只根据核心人设识别。</p>}</div>;
  if (!draft) return <div className="mt-4 rounded-2xl border border-dashed border-indigo-200 bg-indigo-50/60 p-3"><div><p className="text-xs font-bold text-indigo-900">基础作息</p><p className="mt-0.5 text-[10px] leading-relaxed text-indigo-700">还没有作息档案。首次生成日程会只按核心人设识别；你也可以先选择参考世界书再识别。</p></div>{sourcePicker}<button onClick={() => onAnalyze(selectedBookIds)} disabled={busy} className="mt-3 w-full rounded-xl bg-indigo-600 py-2 text-xs font-bold text-white disabled:opacity-50"><Sparkle className="mr-1 inline" size={14} weight="fill"/>{busy ? '识别中' : '按以上依据 AI 识别'}</button></div>;
  const update = (group: 'workday' | 'restday', key: string, value: string) => setDraft(prev => prev ? { ...prev, [group]: { ...prev[group], [key]: value } } : prev);
  return <div className="mt-4 rounded-2xl border border-slate-200 bg-white p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-bold text-slate-700">基础作息</p><p className="mt-0.5 text-[10px] text-slate-500">{draft.summary}</p></div><button onClick={() => onAnalyze(selectedBookIds)} disabled={busy} className="text-[10px] font-bold text-indigo-600 disabled:opacity-50"><Sparkle className="mr-1 inline" size={13} weight="fill"/>{busy ? '识别中…' : '重新识别'}</button></div><p className="mt-2 rounded-lg bg-slate-50 px-2 py-1.5 text-[10px] leading-relaxed text-slate-500">当前识别依据：{sourceSummary}</p>{sourcePicker}<input value={draft.summary} onChange={event => setDraft({ ...draft, summary: event.target.value })} className="mt-2 w-full rounded-lg bg-slate-50 px-2 py-1.5 text-xs outline-none"/><div className="mt-3 grid grid-cols-2 gap-2">{(['workday', 'restday'] as const).map(group => <div key={group} className="rounded-xl bg-slate-50 p-2"><p className="mb-1.5 text-[10px] font-bold text-slate-600">{group === 'workday' ? '工作日 / 补班' : '周末 / 节假日'}</p>{([['wakeTime', '起床'], ['breakfastTime', '早餐'], ['lunchTime', '午餐'], ['dinnerTime', '晚餐'], ['sleepTime', '睡觉']] as const).map(([key, label]) => <label key={key} className="mb-1 flex items-center justify-between text-[9px] text-slate-500"><span>{label}</span><input type="time" value={draft[group][key]} onChange={event => update(group, key, event.target.value)} className="w-[68px] rounded bg-white px-1 py-0.5 text-[10px] text-slate-700 outline-none"/></label>)}{group === 'workday' && <><label className="mb-1 flex items-center justify-between text-[9px] text-slate-500"><span>上班</span><input type="time" value={draft.workday.workStartTime || ''} onChange={event => update('workday', 'workStartTime', event.target.value)} className="w-[68px] rounded bg-white px-1 py-0.5 text-[10px] text-slate-700 outline-none"/></label><label className="flex items-center justify-between text-[9px] text-slate-500"><span>下班</span><input type="time" value={draft.workday.workEndTime || ''} onChange={event => update('workday', 'workEndTime', event.target.value)} className="w-[68px] rounded bg-white px-1 py-0.5 text-[10px] text-slate-700 outline-none"/></label></>}</div>)}</div><button onClick={() => onSave({ ...draft, sourceWorldbookIds: selectedBookIds, sourceWorldbookLabels: worldbooks.filter(book => selectedSet.has(book.id)).map(book => book.title), updatedAt: Date.now() })} className="mt-3 w-full rounded-xl border border-indigo-200 bg-indigo-50 py-2 text-xs font-bold text-indigo-700"><Clock className="mr-1 inline" size={14}/>保存作息</button></div>;
};
export default RoutinePanel;
